# Generated by Django 3.1.4 on 2022-05-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felix',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
